### ISSUE TITLE
Add empty project with Identity

### ISSUE THREAD

**Issue by majco333** [FunnyBean/IntraWeb#1]

**Comment by ivansopoliga** [comment]
Done.

**Comment by Burgyn** [comment]
Ešte asi nemáme konvencie, ale podľa mňa by názov solušnu mohlo začínať veľkým písmenom.
Čo Vy na to?

**Comment by majco333** [comment]
Ja by som dokoncal pouzil CamelCase - teda konkretne IntraWeb, alebo FunnyBean. Preco sme inak projekt aj solution nazvali IntraWeb? Konvencie ma pripravit Gabo a budeme ich pripomienkovat

**Comment by Burgyn** [comment]
Súhlasím s Majom.

**Comment by majco333** [comment]
Cau Mino,
    
    vsimol som si, ze si zacal robit na API. Nezapises to do issues? Aby
    to nahodou nerobil aj niekto iny, pre istotu...
    
    Diki
    
    Majo
    
    Dňa 12.12.2015 o 10:53 Miňo napísal(a):
    
    
      Súhlasím s Majom.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by majco333** [comment]
Este mi napadlo, ci ten vzorovy projekt nezminimalizujeme, neorezeme o nepotrebne veci (HomeController, HomeView...), nech to mame ciste. Co vy na to?

**Comment by Burgyn** [comment]
Čau Majo,
Ja som si chcel len vytvoriť testovací projekt, kde sa budem hrať a skúšať si veci :-)
Ale áno máš pravdu vytvorím na to issue. (Na tu moju branchu môžete zabudnúť, je fakt len testovacia.)
Ešte som chcel vytvoriť labels aby sme si tie issues organizovali. Večer sa možno k tomu dostanem, keď budem mať návrh tak ho pošlem na pripomienkovanie.

BTW, ako si dal koment k môjmu?? Ja to neviem :-(

**Comment by majco333** [comment]
Co k tomu mojmu komentu vyssie? Ideme to minimalizovat alebo netreba?

**Comment by Burgyn** [comment]
Ja som za očistenie.
Budeme mať väčší poriadok.

On 13 December 2015 at 20:06, Majo Mikula <notifications@github.com> wrote:

> Co k tomu mojmu komentu vyssie? Ideme to minimalizovat alebo netreba?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FunnyBean/IntraWeb/issues/1#issuecomment-164288258>.
>



-- 
Prajem pekný zvyšok dňa,
Ing. Milan Martiniak
