### ISSUE TITLE
Vyhodit "zbytocnosti" z inicializacneho projektu

### ISSUE THREAD

**Issue by majco333** [FunnyBean/IntraWeb#10]
Stranky, ktore nie je treba, JS a CSS, ktore nie je treba - cielom je mat len cistu kostru projektu s podporov pre prihlasovanie.

**Comment by ivansopoliga** [comment]
Viete to niekto pozrieť, kým to nahrám do master-a?

**Comment by majco333** [comment]
Jasne, daj pull request, pozrieme...

**Comment by ivansopoliga** [comment]
To by som preniesol zmeny do master-a nie? Nestačí si stiahnúť moju vetvu z githubu?

**Comment by majco333** [comment]
Oki mozem aj tak, ale pull request je prave o tom, ze to nejde do mastera, ale az po potvrdeni...

**Comment by ivansopoliga** [comment]
Aha ok, tak ho môžem spraviť.

Nevedel som čo presne vyhodiť zo Startup.cs. Tak som dal prečo len veci okolo MVC. Ak ešte niečo nepotrebujeme, dajte vedieť.
