### ISSUE TITLE
Rozbehat server v Azure a spustit inicializacny projekt

### ISSUE THREAD

**Issue by majco333** [FunnyBean/IntraWeb#11]
Podklady od Dana:

https://manage.windowsazure.com
intranet@kros.sk

**Comment by majco333** [comment]
Zatial je vytvoreny server:
Windows Server 2012 R2 Datacenter x64 + Visual Studio 2015 Community 
2 CPU, 7 GB RAM

Zatial iba prazdny web je na adrese: http://funnybean.cloudapp.net/

**Comment by majco333** [comment]
Fuha, hotovo... Aktualna verzia z Gihubu sa da skusat tu: http://funnybean.cloudapp.net/
@Burgyn sa da nieco uzivatelsky uz testovat?

**Comment by majco333** [comment]
Kto by sa chcel pripojit cez RDP na server, dajte vediet (nechcem sem davat heslo...).

**Comment by Burgyn** [comment]
Ahoj, nie ešte sa nedá. Je to iba WebApi.
Na užívateľské rozhranie je vytvorená samostatná issue #8
.

On 7 January 2016 at 20:38, Majo Mikula <notifications@github.com> wrote:

> Fuha, hotovo... Aktualna verzia z Gihubu sa da skusat tu:
> http://funnybean.cloudapp.net/
> @Burgyn <https://github.com/Burgyn> sa da nieco uzivatelsky uz testovat?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FunnyBean/IntraWeb/issues/11#issuecomment-169784273>.
>



-- 
Prajem pekný zvyšok dňa,
Ing. Milan Martiniak
