### ISSUE TITLE
Hello world v AngularJS 2.0

### ISSUE THREAD

**Issue by majco333** [FunnyBean/IntraWeb#12]
Rozchodit AngularJS 2.0 v projekte vytvorenim prazdnej stranky s Hello world...

**Comment by ivansopoliga** [comment]
Má niekto chuť sa na to pozrieť? Mne sa dnes za celý deň nepodarilo pohnúť z miesta. Rozbehol som to iba v javascripte, ale ten má dosť divokú syntax. Typescript nič. Na nete toho veľa nie je, väčšinou pre alpha verziu angularu a pravdepodobne to do bety dosť zmenili. Dávam tomu ešte deň a ak sa nikam nepohneme tak by som dal hlasovať medzi angular 1 a reactom. Toto je zbytočná strata času. Čo myslíte?

**Comment by majco333** [comment]
Skus este podla nejakeho ineho postupu (ak je) a ak nie, tak sa dohodneme kto este tomu da sancu...

**Comment by Burgyn** [comment]
Ja som narazil minulý týždeň na toto video https://www.google.sk/url?sa=t&source=web&rct=j&url=https://www.youtube.com/watch%3Fv%3Dbwv8C7WTV5o&ved=0ahUKEwjs-dWupuvJAhXDtBQKHVCPBUwQtwIIIDAC&usg=AFQjCNHtMIi9LKvNWqYbMBRTjSWnbFvxVA&sig2=_1OdXmS2k5TLnH3wOTvNhw
Ale neskúšal som to.

**Comment by ivansopoliga** [comment]
Toto som tiež skúšal. Problém je, že ten 5 min quickstart čo majú na stránke už vyzerá trochu inak ako na videu. Niečo tam zmenili čo nefunguje rovnako. Ešte tomu dám dnes večer, možno robím niečo zle. Prípadne dnes niekto zverejní nový postup pre beta verziu :-)

**Comment by Burgyn** [comment]
Držím palce. Ak sa ti to nepodarí tak sa na to skúsim pozrieť aj ja. Ale čas na to budem mať až niekedy budúci týždeň.

**Comment by ivansopoliga** [comment]
chcem už začať robiť na projekte. nebaví ma naťahovať sa s týmto tu. našiel som dobré referencie na react.js a aj plno videi na pluralsighte. môžem začať robiť v tom alebo je tu niekto, kto je vyslovene za angular 2?

**Comment by Burgyn** [comment]
ja som v pohode aj s reactom

2015-12-23 11:15 GMT+01:00 ivansopoliga <notifications@github.com>:

> chcem už začať robiť na projekte. nebaví ma naťahovať sa s týmto tu.
> našiel som dobré referencie na react.js a aj plno videi na pluralsighte.
> môžem začať robiť v tom alebo je tu niekto, kto je vyslovene za angular 2?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FunnyBean/IntraWeb/issues/12#issuecomment-166855212>.
>



-- 
Prajem pekný zvyšok dňa,
Ing. Milan Martiniak

**Comment by majco333** [comment]
Kludne...

**Comment by Burgyn** [comment]
> Additionally, ReactJS.NET does not support the Core CLR at this point in time, so you will need to ensure your project is not referencing it. Remove the ```"dnxcore50": { }``` line from your project.json file.

Z toho mi vychádza, že zatiaľ je podporovaný iba plný .NET 4.6 framework a nie .NET 5 Core. _(napr.: Nemôžme to nasadiť na linuxovej mašine)_ 
Aj tak do toho ideme? Nie som proti, len sa pýtam.

**Comment by ivansopoliga** [comment]
Za mňa v pohode. V projekte používame plný a pri nasadení pochybujem, že budeme riešiť nasadenie na newindows mašinu. Do vtedy to možno aj dorobia. Ešte je otázka či Reactjs.net vlastne potrebujeme a či sa nezaobídeme bez neho.

**Comment by majco333** [comment]
Ja by som bol za multiplatforms - teda ak to pojde, silit to nemusime...

**Comment by ivansopoliga** [comment]
našiel som aj inú knižnicu pre transformáciu JSX súborov, takže .NET 5 Core by mohol zostať v projekte ... pobavíme sa o tom na nejakom stretnutí po novom roku, lebo pojmov a otázok je tam viac. 

https://www.pluralsight.com/courses/react-flux-building-applications

**Comment by Burgyn** [comment]
Ahojte,
chcem dať ešte šancu **angular-u 2**.
Zajtra večer sa na to pozriem.

**Comment by ivansopoliga** [comment]
ahoj, super. vyzerá to dobre. ideme to použiť alebo aký je postup?

napadlo ma ešte k tomu pár otázok na ktoré by sme si mali odpovedať.
vieme prečo chceme radšej angular 2? (výhody oproti react)
nebude problém s typescriptom pri použití ďalších javascript knižníc?
aké veľké je riziko, že to budeme musieť prerobiť až vydajú novšiu verziu, prip. môžeme ostať na bete?

**Comment by Burgyn** [comment]
no práve aby sme to vedeli porovnať som to chcel vyskúšať. Chcem ešte skúsiť pripojiť sa na web api a  zobraziť nejaké dáta (zoznam miestností). Dám tomu dnešný večer. Potom navrhujem, aby sme sa k tomu stretli osobne. A prediskutovali to.
Pretože je tam pre mňa veľa otázok :-)
Vedel by si pripraviť tiež jednoduchý príklad na react?

**Comment by ivansopoliga** [comment]
ok, urobím niečo podobné v reacte

**Comment by Burgyn** [comment]
Vytvoril som demo príklad v testovacej vetve nášho projektu ```MinoAngular2Test```
Je tam jednoduchá aplikácia, ktorá spája dva texty a zložitejšia, ktorá načítava zoznam miestností z nášho web api. 
 >ak by vám to nezobrazilo miestnosti, tak skontrolujte url adresu v súbore roomsApp.ts či má správny port.

**Comment by Burgyn** [comment]
Teraz som narazil na zaujímavý príklad na ASP.NET 5 a AngularJs 2.0 SPA aplikáciu.
http://chsakell.com/2015/12/31/cross-platform-single-page-applications-with-asp-net-5-angular-2-typescript/

**Comment by majco333** [comment]
Parada, uz to len rozbehat :)
    
    Majo
    
    Dňa 7.1.2016 o 19:43 Miňo napísal(a):
    
    
      Teraz som narazil na zaujímavý príklad na ASP.NET 5 a AngularJs
        2.0 SPA aplikáciu.
        http://chsakell.com/2015/12/31/cross-platform-single-page-applications-with-asp-net-5-angular-2-typescript/
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Burgyn** [comment]
Rozbehané to je, tak ako píšem v príspevku vyššie. Toto je taký
komplexnejší príklad.

2016-01-07 20:47 GMT+01:00 Majo Mikula <notifications@github.com>:

>
>
>
>
>
> Parada, uz to len rozbehat :)
>
> Majo
>
> Dňa 7.1.2016 o 19:43 Miňo napísal(a):
>
>
> Teraz som narazil na zaujímavý príklad na ASP.NET 5 a AngularJs
> 2.0 SPA aplikáciu.
>
> http://chsakell.com/2015/12/31/cross-platform-single-page-applications-with-asp-net-5-angular-2-typescript/
>
> —
> Reply to this email directly or view
> it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FunnyBean/IntraWeb/issues/12#issuecomment-169786689>.
>



-- 
Prajem pekný zvyšok dňa,
Ing. Milan Martiniak

**Comment by ivansopoliga** [comment]
Urobil som podobny priklad v reacte. Ak by to niekomu nefungovalo prip. ma ine pripomienky dajte vediet.

**Comment by Burgyn** [comment]
Vyzerá to pekne.
