### ISSUE TITLE
Vytvorenie kostry hlavnej stránky

### ISSUE THREAD

**Issue by Burgyn** [FunnyBean/IntraWeb#15]
Ideme robiť SPA aplikáciu, tak je potrebné vytvoriť kostru hlavnej stránky aplikácie.
Horné menu, možno nejaký footer a hlavný priestor, kde sa budú zobrazovať jednotlivé časti aplikácie.

**Comment by ivansopoliga** [comment]
ahojte, vychádza mi z tohto potreba nejakých zmien, lebo momentálne nemám ts a html pri sebe a ešte musím pridať less a niekam ho kompilovať.

prvá možnosť:
všetky súbory budú v priečinku Scripts v hlavnom adresári. tak zabezpečíme, že budeme mať všetko čo sa týka každého komponentu pokope. ts sa bude kompilovať tam, kde je zdrojový súbor. visual studio ho pekne schová pod taký zobák. 
teraz ako všetko dostanem do wwwroot ... 
upravím gulp, aby spravil pri builde projektu tieto kroky:
1. vymaže celý obsah wwwroot/app priečinka
2. nakopíruje zo Scripts do wwwroot/app všetky súbory .js a .html (štruktúra ostáva zachovaná)
3. skompiluje z priečinka Scripts všetky súbory .less a nakopíruje ich do wwwroot/app

výsledok po builde:
wwwroot
 app
  login
    login.component.js
    login.component.html
    login.component.css
.
Scripts
 app
  login
   login.component.ts
   login.component.html
   login.component.less

druhá možnosť:
všetko bude vo wwwroot/app, ale budú tam zbytočne .ts a .less súbory, tzn. ku niektorým komponentom budem mať 5 súborov :-)

wwwroot
 app
  login
   login.component.ts
   login.component.js
   login.component.html
   login.component.less
   login.component.css

pre tých, čo nerozumejú: 
každý angular komponent (napr. login formulár) sa nachádza v súbore nazov.component.ts, ktorý pri uložení VS automaticky kompiluje na nazov.component.js. okrem tohto má komponent svoj template (html kód) v súbore nazov.component.html. takisto môže mať svoj nazov.component.css súbor s popisom zobrazenia. dohodli sme sa však, že nepoužívame klasické css, ale less formu. tak vznikne súbor s príponou .less, ktorý treba pred použitím skompilovať na css.

dajte prosím vedieť čo sa vám viac pozdáva, aby som mohol pokračovať. ja som skôr za prvú možnosť. príde mi čistejšia. časom môžeme napr. zrušiť automatickú konverziu ts súborov (nie je to úplne spoľahlivé, o tom si povieme na stretnutí) a tiež to nechať až na gulp.

**Comment by majco333** [comment]
Ja som za prvu moznost

**Comment by Burgyn** [comment]
Ja som za prvu moznost

**Comment by Burgyn** [comment]
Tato issue sa uz asi moze uzavriet, ci?
