### ISSUE TITLE
Míting - 13.01.2016 o 15:00

### ISSUE THREAD

**Issue by majco333** [FunnyBean/IntraWeb#16]
Dohodnute body:
- [x] @ivansopoliga skusi spravit graficky a UX prototyp aplikácie (napr. cez https://marvelapp.com/ )
- [x] @majco333 vytvorí Javascriptové konvencie
- [x] @DanielHolan naplní názvy US do milestone pre rezerváciu miestností 
- [x] @DanielHolan zistí, či môžeme mať na pracovných PC nainštalované VS 2015 Community edition
- [x] Uzavrieme to, ako nám môže firma vyjsť v ústrety v tejto fáze projektu.
* Rozhodli sme sa pre Angular. Skúsime aplikáciu robiť v ňom.
* Každý Pull request treba aby niekto pozrel (garantov zdrojákov zatiaľ nepotrebujeme)
* Rozhodli sme sa robit plnu SPA aplikaciu (bez MVC stranok...)
* Robíme unit testy aj pre serverovskú aj klientskú časť.

**Comment by Burgyn** [comment]
Ešte doplním, že sme sa dohodli, že robíme plnú SPA. 
Takže zatiaľ všetky sekcie sa budú zobrazovať v rámci jednej stránky.

**Comment by ivansopoliga** [comment]
Potreboval by som sa s vami dohodnúť na štruktúre projektu. Ako budeme štrukturovať prečinky, čo kde budeme ukladať. Možno dohodnúť aj základnú kostru komponentov na stánke, keďže bude všetko angular. Ideme to dohodnúť tu alebo to necháme na stretko?

**Comment by Burgyn** [comment]
Mohol by si na to vytvoriť samostatné issue.
Môžeme tam dávať nápady, poprípade odkazy na články kde je niečo také riešené. Ak na stretku to dorazíme. Ja chcem zajtra doraziť tie unit testy až môžem uzavrieť ten zoznam miestností a popri tom si niečo k tomu naštudovať. Ale nesľubujem :-)

**Comment by Burgyn** [comment]
Ešte som si spomenul, že sme sa na tomto mítingu dohodli, že robíme unit testy aj pre serverovskú aj klientskú časť.
