### ISSUE TITLE
Ako nám môže firma vyjsť v ústrety

### ISSUE THREAD

**Issue by majco333** [FunnyBean/IntraWeb#19]
Nápady:
* koordinačné stretko bude v rámci pracovného času (cca 1,5 hodiny týždenne)

Čo ďalej?

**Comment by DanielHolan** [comment]
- možnosť konzultácii s ľuďmi vo firme počas pracovnej doby 
(ohľadom funkcii - ľudí, ktorých sa to týka, prípadne aj medzi sebou - krátke 5-10 minútové konzultácie)
-  využívať server v azure na testovanie (officiálne)

**Comment by motycak** [comment]
- platené konto na GitHube - kódy prístupné iba pre nás

**Comment by majco333** [comment]
Prejdem to s Tomasom...

**Comment by majco333** [comment]
Mam vyjadrenie od Tomasa (preberieme zajtra):

* koordinačné stretko bude v rámci pracovného času (cca 1,5 hodiny týždenne) 
  * OK, nejako to ale nesmie ovplyvniť záväzky tímov, kde ľudia sú
* možnosť konzultácii s ľuďmi vo firme počas pracovnej doby (ohľadom funkcii - ľudí, ktorých sa to týka, prípadne aj medzi sebou - krátke 5-10 minútové konzultácie) 
  * OK
* využívať server v azure na testovanie
  * OK
  * platené konto na GitHube - kódy prístupné iba pre nás Koľko to stojí?

·         Potom ja by som ponúkol to, že človek, ktorý bude robiť užívateľskú analýzu by mohol ísť na školenie UX.
·         Ďalej bolo by fajn, ak by ste mali nepravidelné demo a to v čase niekedy od 07:30 – ľudia budú mať záujem to vidieť.
·         Ja by som chcel pred tým ako sa to spustí vidieť nejaký návrh štruktúry (ako bude vypadať stránka) a nejaký hrubý plán aké moduly sa idú robiť

**Comment by majco333** [comment]
@DanielHolan  porzri prosim na tie balicky Githubu, ci mozeme pouzit Micro personnal balik...

**Comment by majco333** [comment]
@majco333 prever UX skolenie a kedy ten navrh chce vidiet...
