### ISSUE TITLE
Oprava adresárovej štruktúry

### ISSUE THREAD

**Issue by satano** [FunnyBean/IntraWeb#2]
Trochu sme sa nepochopili s tou adresárovou štruktúrou. Adresár `src` je adresár, kde sú komplet zdrojáky so všetkým čo s nimi súvisí. Solution a projekty sú priamo v ňom, nie naopak. Teda teraz je to takto:

- intraweb
    - src
        - intraweb (projekt)
    - intraweb.sln

Lepšie by to bolo takto:

- src
    - lib
    - intraweb (projekt)
    - intraweb.sln

Ďalej predpokladám, že budeme mať nejaké externé pomocné DLL-ky či iné knižnice tretích strán. Preto by sa ešte hodila zložka `lib` tiež priamo pod `src` (tzn. na úrovni `.sln`). Tam sa tieto knižnice dajú a v projektoch sa referencujú lokálne odtiaľ.

**Comment by Burgyn** [comment]
S tou adresárovou štruktúrou som si nie istý. 
Pretože odporúčanie pre ASP.NET 5 je práve taká adresárová štruktúra, že samotné solution je nad adresárom src. http://docs.asp.net/en/latest/conceptual-overview/understanding-aspnet5-apps.html
Treba to premyslieť aj z ohľadom na to.

**Comment by satano** [comment]
Hm. To som nevedel. Teda to tak zjavne vygenerovalo VS. OK teda. Keď už má MS nejaký štandard, tak nejdem nasilu proti nemu. Ak nikto nič nemá, pokojne to uzavriem, že je to dobré tak ako to je.

Potom teda zložka `lib` a prípadne iné budú na úrovni `src`.

**Comment by Burgyn** [comment]
OK.
Čo sa týka toho `lib` adresára tak ten uvidíme, či budeme potrebovať. Keďže väčšinu vecí budeme mať asi cez `nuget` `Bower`a `nmp`. Ale veď čas ukáže.
Ja som za uzavretie.
