### ISSUE TITLE
Implementovať IEmailSender

### ISSUE THREAD

**Issue by Burgyn** [FunnyBean/IntraWeb#20]
Implementovať IEmailSender na odosielanie emailov.
Budeme ho už čoskoro potrebovať.

**Comment by majco333** [comment]
Otazky:
• budeme odosielat uzivatelske emaily alebo aj servisne (chyby)?
• nastavenia smtp dame do konfiguraku aplikacie?
• pouzijeme gmailove smtp?
• budu to html emaily?

**Comment by Burgyn** [comment]
Časom asi aj servisne aj užívateľské. Teraz hlavne potrebujeme užívateľské. Keďže nebudeme mať klasickú registráciu, ale admin bude pridávať používateľov, tak musíme nejak vyriešiť ako sa človek dozvie svoje heslo.

- nastavenia by som dal určite do konfigu. (aj keď pri ASP.NET 5 nie je potrebné buildovať aplikáciu pri zmene zdrojákov, ale aj tak)
- ja by som zatiaľ použil gmailove smtp
- a asi áno, mali by to byť html emaily.

Mal by tej triede predchádzať interface, môže byť ten čo už v projekte je vygenerovaný IEmailSender. Aby sme vedeli využiť DI.

Toľko môj názor :-)

**Comment by DanielHolan** [comment]
- Aj ja som za to aby boli užívateľské aj servisné emaily.
- ako je to myslené, že smtp bude v konfiguráku aplikácie? Ja by som bol za to, aby sa dalo smtp meniť správcom. (zatiaľ pre testovanie ale môžeme použiť gmail smtp)
- môže byť HTML, ale pokojne aj plain text - tu by som šiel cestou jednoduchosti :)

toť názor môj

**Comment by majco333** [comment]
Emaily su pri debugu odosielane z gmailoveho SMTP. Na Azurovom serveri to neslo a musel som na to pouzit sluzbu na to urcenu (SindGrid umoznuje odosielat 25 000 emailov za mesiac gratis). Odosielanie z ostretho servera trva 1-2 minuty (je to pomale), pri debugu okamzite.

@Burgyn Nevedel som, ci a ako to UnitTestovat. Pozri na to a daj pripadne tip...

Testovat sa to da zatial zavolanim url: http://funnybean.cloudapp.net/api/email/##EMAIL##
kde ##EMAIL## nahradte vasom emailovou adresou.

Testovaci email vyzera zatial takto:
![image](https://cloud.githubusercontent.com/assets/4101721/12700930/d8efcc74-c7f6-11e5-882b-baff6b6db4db.png)

**Comment by Burgyn** [comment]
Keďže je tam potenciál, že odosielanie môže byť pomalé, nechceme to mať **asynchrónne**?
Vo väčšine prípadov nepotrebujem čakať kým sa to reálne odošle.

Na tie unit testy kuknem

**Comment by Burgyn** [comment]
Mne sa to na gmaily zobrazilo nasledovne 

![image](https://cloud.githubusercontent.com/assets/5930822/12702010/688e7b72-c81b-11e5-8ed3-0a49cc0c6f78.png)

Je niečo zle u mňa?

**Comment by majco333** [comment]
Takto - v kode to spracuje v podstate okamzite, ale na email to pride tak do 1-2 minut. Mam to aj tak spravit asynchronne uz teraz?

Co sa tyka templaty, tak tu som nasiel na webe a popisovali, ze je odladena. Ale asi teda nebude :-) Mozeme najst nieco viac odladene, len neviem ci uz teraz, ked nemame grafiku?

**Comment by majco333** [comment]
Tato nova template by mala byt ovela lepsia:
http://templates.cakemail.com/details/basic

![image](https://cloud.githubusercontent.com/assets/4101721/12703173/e931268c-c83c-11e5-9b5f-e6c71e89f907.png)

**Comment by DanielHolan** [comment]
Tá druhá template vyzerá celkom OK z pohľadu grafiky. 
Za mňa ju môžeš použiť aj keď nie je ešte grafika daná, hodí sa ku všetkému :)
Vo finále by bolo dobre, keby sa dali meniť a pridávať nové.

**Comment by Burgyn** [comment]
V tom prípade netreba. Ja som myslel, ze uz na nasej strane to trva 1min.

**Comment by majco333** [comment]
Doplnit este EmailFormatter class
