### ISSUE TITLE
Verzionovanie API + Base controller

### ISSUE THREAD

**Issue by majco333** [FunnyBean/IntraWeb#28]

**Comment by majco333** [comment]
Rozhodol som sa pre verzionovanie cez URL (pride mi to asi najlepsie). Vytvoril som na to namespace "v1", tak ako odporucaju. V URL nie je pre zakladne api ziadna verzia (nemame .../api/v1/... ale .../api/..), ak budeme pridavat napr. verziu "v2", tak URL bude .../api/v2/...

Zabezpecenie vsetkych kontrollerov som spravil cez BaseController - skusal som aj vseobecnym nastavenim vo Startup.cs.

**Comment by Burgyn** [comment]
Za mňa OK. Asi sa to môže uzavrieť
