### ISSUE TITLE
Rozšíriť web api pre správu miestností o vybavenie

### ISSUE THREAD

**Issue by majco333** [FunnyBean/IntraWeb#29]
V súčastnosti máme Web api pre spracovanie miestnosti. 
Chceme ho ale rozšíriť o možnosť zadávania vybavenia danej miestnosti.
- [x] model a migration
- [x] generické repository
- [x] view model pre equipment a mapovanie
- [x] controller pre equipments
- [x] unit testy pre equipment controller
- [x] ViewModel pre RoomEquipment
- [x] rozšíriť Room o Type
- [x] rozšíriť RoomsController o získanie zoznamu typov miestností
- [x] rozšíriť RoomsController o equipments a unit testy
- [x] dokumentácia (Api a Generické repository)
- [x] 204 nahradit za 404

**Comment by Burgyn** [comment]
V súčastnosti máme Web api pre spracovanie miestnosti. 
Chceme ho ale rozšíriť o možnosť zadávania vybavenia danej miestnosti.
- [ ] číselník vybavenia - vlastný controller
- [ ] rozšíriť RoomsController o vybavenie
- [ ] unit testy

**Comment by Burgyn** [comment]
Ahojte,
mám otázku.
Robím nové api na prácu s vybavením (klasické CRUD operácie).
Počas toho som si uvedomil, že je veľmi podobné s RoomsController-om.
[EquipmentsController](https://github.com/FunnyBean/IntraWeb/blob/MinoEquipments/IntraWeb/src/IntraWeb/Controllers/Api/v1/EquipmentsController.cs) a [RoomsController](https://github.com/FunnyBean/IntraWeb/blob/MinoEquipments/IntraWeb/src/IntraWeb/Controllers/Api/v1/RoomsController.cs)

Nepáči sa mi to. Ale tiež sa mi nepáči to, že by som vytvoril generického predka, ktorý by pokryl spoločnú funkčnosť. Ešte ma napadlo, že by som spoločné veci vytiahol do samostatnej triedy, a riešil by som to kompozíciou. Ale nejak sa neviem rozhodnúť. Zatiaľ si neviem predstaviť, že či budeme mať do budúcnosti podobné controller-y.

Aký je Váš pohľad na vec?
 - Mám to nechať tak? :-)
 - Generický predok?
 - Kompozícia?
 - Iné riešenie?

Dik.

**Comment by majco333** [comment]
Mne sa to tak ako to mas aktualne v branchi (genericky predok) velmi paci a aj to v praxi tiez tak pouzivame. Podla mna je to velmi fajn. Tu kompoziciu neviem presne ako myslis...

**Comment by Burgyn** [comment]
V branchi mám zatiaľ generického predka na repository. S tým som v pohode. Teraz sa skôr zamýšľam nad controllermi. [EquipmentsController](https://github.com/FunnyBean/IntraWeb/blob/MinoEquipments/IntraWeb/src/IntraWeb/Controllers/Api/v1/EquipmentsController.cs) a [RoomsController](https://github.com/FunnyBean/IntraWeb/blob/MinoEquipments/IntraWeb/src/IntraWeb/Controllers/Api/v1/RoomsController.cs)

Tam je to dvojmo. 
Čo sa týka kompozície, tak to som myslel tak. Že by vznikla trieda, ktorá by mala metódy Get, Put, Post, Delete, ... ktoré by implementovali základnú funkčnosť. Teda overenie, či záznam už neexistuje, uloženie dát cez reposiotry, návratové stavy pre response, ... 
Controller by len preposielal požiadavky na inštanciu tejto triedy a špecifiká by si riešil sám. Tá trieda by dostala odkaz na repository a pravdepodobne pomocou lambda expression odkaz na funkciu, ktorá by robila overovanie existencie podľa násvu / popisu.

Kompozícia sa mi pozdáva viac preto, že keď budeme robiť ďalší controller, ktorý bude mať napríklad iný typ kontroly na unikátnosť tak by sme museli upravovať predka tak aby si mohol niečo overridnuť, ... Následne keď budeme potrebovať iný typ controllera, ktorý bude mať časť funkčnosti podobnej, ale väčšiu už nie, tak dedičnosť už nemá význam. 
Preto ma napadlo, že to vyriešim kompozíciou.

**Comment by majco333** [comment]
Aha, zle som ci precital otazku. Myslel som, ze sa pytat na repository, sorry...
Podla toho co pises, tak tu ma kompozicia asi fakt lepsie opodstatnenie. Za mna, skus ist touto cestou a uvidime - prinajhorsom sa to prerobi :-)
