### ISSUE TITLE
Míting č. 2 - 9. 12. 2015

### ISSUE THREAD

**Issue by satano** [FunnyBean/IntraWeb#3]
- [x] **Všetci** si vytvorte kontá na GitHube a pošlite ich **Gabovi**, aby vás pridal do nášho projektu.
- [x] @satano spíše návrh konvencií a dá ich do wiki na pripomienkovanie.
- [x] **Ivo** založí čistý projekt a na ňom potom môžeme stavať (nikdy nerobiť na hlavnej master branci, ale vždy si vytvoriť vlastný).
- [x] **Dano** pridá do aliasu nového člena **Peťa Motyčáka**
- [x] Prebehne ešte stretko s riaditeľom a so Spišom, aby sme sa dohodli ku vzájomnej spokojnosti a aj o tom či firma tento projekt vie nejako podporiť... – dáme vedieť výsledok
- [x] Dohodnúť konvencie písania kódu
- [ ] Dohodnúť si garantov zdrojákov (codereview)

Soft na prácu s GitHubom čo ukazoval Gabo je [GitHub for Desktop](https://desktop.github.com/)

Vidíme sa v novom roku, dovtedy study a môžeme postupne pracovať na dopĺňanie drobností do projektu (lokalizácia, logging...)

**Comment by majco333** [comment]
Stretko s riaditelom a Spisom dopadlo v pohodicke, vyjasnili sme si veci.
Tomas ma este prejst so Šanom, ci je takato iniciativa v pohode (Sano zastava nazor, ze clovek by sa nemal venovat viacerym veciam naraz...). Da nam vediet.
Vidim to ale pozitivne, nic nam zatial nebrani ist sposobom ako doteraz (v buducnosti je mozne, ze firma nas nejako podpori...).

**Comment by majco333** [comment]
Od firmy mame zelenu!!! Takze super, ide sa dalej, tesim sa...

**Comment by majco333** [comment]
Zatvaram, dohodnute garantov presuvam na dalsie stretka...
