### ISSUE TITLE
Konvencia písania zdrojákov

### ISSUE THREAD

**Issue by satano** [FunnyBean/IntraWeb#4]
Vytvoril som dokument [Konvencii písania zdrojákov](https://github.com/FunnyBean/IntraWeb/wiki/Konvencia-p%C3%ADsania-zdroj%C3%A1kov).

Dal som tam len to čo považujem za základné, ale to neznamená, že som na niečo základné nezabudol. Kto má pripomienky/návrhy, spisujte ich sem. Čo bude treba, do dokumentu doplníme.

**Comment by Burgyn** [comment]
Ja som za to aby public interface tried mal 'xml' komentáre.

**Comment by satano** [comment]
Časť o komentároch je pridaná.

**Comment by majco333** [comment]
Moje navrhy:
1.) Konštanty
do notuse Screaming Caps for constants or readonly variables
// Correct
public static const string ShippingType = "DropShip";
 
// Avoid
public static const string SHIPPINGTYPE = "DropShip";

Alebo ideme do konstant stylom AP_WIN_MIN_WIDTH ?

2.) Ten podčiarkovník v privátnych memberoch objektu sa mi nikdy nepáčil a bije mi to očí :-) a pripomína mi to nečitateľný C++ kód. Nevieme to inak vymyslieť?
3.) Máme jasno v tom akým jazykom (eng, svk) píšeme komentáre?
4.) Tu je to inak celkom pekne, vystizne: http://www.dofactory.com/reference/csharp-coding-standards  Nechceme ešte z toho pridať?
5.) Používanie var mi moc nesedí, mám radšej keď vidím priamo akého je premenná typu - ideme to striktine dodržiavať?
6.) Toto by som rád:
declare all member variables at the top of a class, with static variables at the very top.
// Correct
public class Account
{
    public static string BankName;
    public static decimal Reserves;
 
    public string Number {get; set;}
    public DateTime DateOpened {get; set;}
    public DateTime DateClosed {get; set;}
    public decimal Balance {get; set;}
 
    // Constructor
    public Account()
    {
        // ...
    }
}

Neskor asi budeme musiet rozsirit konvencie aj pre:
Javascript: http://www.w3schools.com/js/js_conventions.asp
HTML: http://www.w3schools.com/html/html5_syntax.asp
CSS: http://www.w3schools.com/css/css_syntax.asp
mozno Angular: http://www.w3schools.com/angular/angular_intro.asp

**Comment by Burgyn** [comment]
2.) podčiarkovník - ja som na neho z C# zvyknutý. Dobre s ním pracujú aj refaktorovacie nástroje. Ale ak vymyslíme niečo iné tak si zvyknem. 
3.) Tiež ma zaujíma jazyk. Ja som za eng. Viem, že nie všetci vieme dobre po anglicky (ja tiež neviem), ale je to aspoň príležitosť sa to naučiť. 
5.) var - určite by som nechcel aby to bolo striktné. Ja ale rád používam var. Typ by mal byť jasný už z názvu premennej. Keď sa niečo volá count tak je jasné, že je to int. Keď sa niečo volá person tak to bude typu Person. A častokrát to bez var-u ani nejde (pri používaní linku a anonymných tried).


Toľko môj názor.

BTW - nevie mi niekto poradiť ako reagovať na konkrétny komentár v danej issue? Dá sa to vôbec? Dik.

**Comment by majco333** [comment]
Mozno priamo odpisanim na email ako pisem aj teraz - ak teda myslis toto...

**Comment by Burgyn** [comment]
Aha. To ma nenapadlo. Vždy som to robil priamo cez GITHUB.
Ďakujeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeem.

2015-12-13 12:13 GMT+01:00 Majo Mikula <notifications@github.com>:

> Mozno priamo odpisanim na email ako pisem aj teraz - ak teda myslis toto...
> On Dec 13, 2015 11:54 AM, "Miňo" <notifications@github.com> wrote:
>
> > 2.) podčiarkovník - ja som na neho z C# zvyknutý. Dobre s ním pracujú aj
> > refaktorovacie nástroje. Ale ak vymyslíme niečo iné tak si zvyknem.
> > 3.) Tiež ma zaujíma jazyk. Ja som za eng. Viem, že nie všetci vieme dobre
> > po anglicky (ja tiež neviem), ale je to aspoň príležitosť sa to naučiť.
> > 5.) var - určite by som nechcel aby to bolo striktné. Ja ale rád používam
> > var. Typ by mal byť jasný už z názvu premennej. Keď sa niečo volá count
> tak
> > je jasné, že je to int. Keď sa niečo volá person tak to bude typu
> Person. A
> > častokrát to bez var-u ani nejde (pri používaní linku a anonymných
> tried).
> >
> > Toľko môj názor.
> >
> > BTW - nevie mi niekto poradiť ako reagovať na konkrétny komentár v danej
> > issue? Dá sa to vôbec? Dik.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/FunnyBean/IntraWeb/issues/4#issuecomment-164247101>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FunnyBean/IntraWeb/issues/4#issuecomment-164247706>.
>



-- 
Prajem pekný zvyšok dňa,
Ing. Milan Martiniak

**Comment by majco333** [comment]
Takze to ide? :) Som zmeteny, lebo vyzera ze vsetky komenty su priamo pre issue

**Comment by Burgyn** [comment]
Čiastočne. Keď odpíšem cez mail tak aspoň vidieť, že reagujem na niečo
konkrétne.
Aspoň niečo.

On 13 December 2015 at 12:16, Majo Mikula <notifications@github.com> wrote:

> Takze to ide? :) Som zmeteny, lebo vyzera ze vsetky komenty su priamo pre
> issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FunnyBean/IntraWeb/issues/4#issuecomment-164247796>.
>



-- 
Prajem pekný zvyšok dňa,
Ing. Milan Martiniak

**Comment by satano** [comment]
1. Konštanty - jasné. Patrí to do časti PascalCase. Vlastne je to tam zahrnuté v slovných spojeniach "všetko ostatné" a v troch bodkách na konci, ale dopíšem. :)

2. Ja som zvyknutý. Je mi jedno čo bude &ndash; prispôsobím sa &ndash; ale niečo na toto treba asi.

3. Jazyk v komentároch nemáme jasno. Nech sa vyjadria ostatní. To nechám na *demokratickú väčšinu* a prispôsobím sa. Ale v angličtine môže byť problém pri vyjadrovaní.

4. Pozrel som to a súhlasím takmer so všetkým v tom dokumente. Ale v podstate mne nepríde, že by sme museli explicitne (zatiaľ) niečo z toho pridávať. Nechcem som ten dokument robiť príliš veľký. Však sa časom môže rozširovať podľa potreby.

5. Používanie `var` nie je striktné a rovnako v tomto voľnom duchu je to aj napísané v dokumente. Ide o to, že hlavne keď rovno vytváraš inštanciu, tak rovno vidíš akého je premenná typu &ndash; a o toto ide aj tebe: `var idList = new List<int>()` Vieš, že tá premenná je typu `List<int>` a nemusíš to vypisovať aj pred jej názvom, aj za ním. Rovnako ako je to vo Visual Basicu, kde ti tiež stačí napísať `Dim idList As New List(Of Int32)` a nie ako kedysi `Dim idList As List(Of Int32) = New List(Of Int32)`. U mňa toto bolo hrozne návykové a používam to prakticky na všetko, čo sa rovno inicializuje. Teda napríklad aj `Dim name = "Janko Hraško"` &ndash; keď sa pozriem na premennú, rovno viem, že je typu `String`.

6. Ak to bude ľuďom vyhovovať, môže byť. Ja som zvyknutý väčšie triedy organizovať do menných priestorov, pričom tie sú podľa logiky ktorú zastrešujú. A teda mám vlastnosti "rozhádzané" spolu s metódami v jednotlivých blokoch. Ale mne moc nesedí, že konštruktor môže byť potom zahrabaný niekde príliš ďaleko. :) Je to fpohode, ak drvivá väčšina tých vlastností bude takto pekne automaticky implementovaných &ndash; každá na jeden riadok.

**Comment by DedrickX** [comment]
1. Konštanty mi osobne sedia PascalCase, nemám príliš rád Caps...
2. Konvencia podčiarkovníka ako prefixu privátnych premenných je v C# rozšírená a ja osobne som si na ňu už zvykol vďaka Resharperu, ktorý ma do nej tlačil... :). Ale zvyknem si na čokoľvek.
3. V komentároch bude moja angličtina možno trochu na smiech, ale posnažím sa :)
5. var nemusí byť striktné... ale akonáhle človek začne vo veľkom pracovať LINQ a IQueryable čudesnosťami, vypisovanie dátových typov vie byť otravné. Takže tu by som nerád nútil vývojárov do jednej konkrétnej cesty...

A ku JavaScriptu budú tiež nejaké konvencie?. Tam to bude celkom zaujímavé :)...

**Comment by majco333** [comment]
Oki, tak za mna teda moze byt, so vsetkym suhlasim.
Otazka - viem nejako rozdelit tu konvecniu, tak aby tam boli zalozky? Pridal by som tam neskor konvencie pre Javascript...

**Comment by satano** [comment]
Vieme. :smile:

**Comment by Burgyn** [comment]
Mali by sme sa dohodnúť aj na tom, ako nazývať **Controllery** a **Repository**. Ja keď programujem tak mám vždy problém, či ich nazývať množným alebo jednotným číslom. _RoomsControler_ vs _RoomControler_.
Taktiež by bolo fajn jednotne nazývať metódy pre WEB API. 
Napr.: Metóda Get ktorá vracia zoznam entít sa niekde nazýva iba Get inde GetRooms, ...
Majo ako to máte u Vás na projekte?

Bolo by pekné keby sme to mali jednotné.

**Comment by majco333** [comment]
My pouzivame mnozne cislo a iba Get. Priklad ako to vyzera potom:
![a](https://cloud.githubusercontent.com/assets/4101721/11876011/c56b3bca-a4e7-11e5-8059-b556589b6689.PNG)
Viac tu: http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api

**Comment by Burgyn** [comment]
A čo databázové konvencie? Samé veľké písmená, alebo PascalCase?

**Comment by majco333** [comment]
Ja som jednoznacne za PascalCase...

**Comment by satano** [comment]
Ja tiež. Samé veľké/samé malé písmená sú nečitateľné, pokiaľ daný reťazec nie je jednoslovný.

**Comment by Burgyn** [comment]
Ja som tiež za.

**Comment by ivansopoliga** [comment]
pozerám angular tutorial a pre súbory komponentov používajú názov meno.component.ts, pre služby meno.service.ts, atď. navrhujem, aby sme rovnáke pravidlo dodržali aj my. ste za?

**Comment by Burgyn** [comment]
Ja som za

**Comment by majco333** [comment]
Moze byt...

**Comment by majco333** [comment]
Naposledy sme sa bavili, ze skusim spisat konvencie pre Angular kod. Co pozeram, tak je toho celkom dost, nasiel som nieco taketo (ale zda sa mi to asi zbytocne rozsiahle). Mam z toho urobit iba taky najzakladnejsi vycuc?

https://mgechev.github.io/angularjs-style-guide/
https://github.com/johnpapa/angular-styleguide

**Comment by DedrickX** [comment]
Myslím že by bol nejaký výcuc fajn... Aj veci týkajúce sa JavaScriptu ako takého.
A to v tých linkoch sú konvencie týkajúce sa Angularu všeobecne, bez ohľadu na verziu? Keď je tá dvojka tak odlišná od jednotky :)...

**Comment by Burgyn** [comment]
Ja som tiež za výcuc. 
Také základy.

Ten prvý článok je fajn aj z hľadiska štruktúry projektu, čo práve chce riešiť Ivo.

**Comment by majco333** [comment]
Tu je prvy nastrel, mozete pripomienkovat:
- moze to byt v Eng?
- pre Angular som dal iba par veci. Budeme to rozsirovat postupne, tak ako sa to budeme ucit... 

https://github.com/FunnyBean/IntraWeb/wiki/Konvencia-p%C3%ADsania-zdroj%C3%A1kov-Javascript-a-Angular
