### ISSUE TITLE
Vytvorenie našich štítkov pre Issues

### ISSUE THREAD

**Issue by Burgyn** [FunnyBean/IntraWeb#5]

**Comment by satano** [comment]
Máš aj nejaké nápady? Nevyplynie to postupne zo situácií? Ako napríklad tá organizácia. :wink:

**Comment by Burgyn** [comment]
Chcel som vytvoriť issue na web api pre spravovanie miestností. 
Rozmýšľal som, že by bolo dobré ju nejak označiť aby bolo jasné, že toto sa týka už úlohy na zapracovanie do projektu. Tak ma napadlo, že by sa hodil label niečo ako 'user story' poprípade 'backlog'. Následne ma napadlo, že by bolo fajn jej dať aj nejaký label podľa stavu 'in progress' aby bolo jasné že na nej už robím. 
Tak som si povedal, že si dám issue kde skúsim navrhnúť tento spôsob fungovania (odkukať ako to robia inde) a dám to na spripomienkovanie.
Takže preto táto issue.

**Comment by Burgyn** [comment]
Dočítal som sa nasledovné:
väčšina rozdeľuje štítky do dvoch základných kategórií:
* **ISSUE TYPE**
 - **task** - štandardná úloha na riešenie
 - **bug** - hlásená chyba
 - **feature** - námet na vylepšenie. 
 - **discussion**
 - **refactor** - potrebný refaktor
 - **...**

* **WORKFLOW**
 - **0 - Backlog** (úloha ktorú chceme riešiť, ale ešte ju nie je možné realizovať. Je potrebná ďalšia diskusia, ...)
 - **1 - Ready** (pripravená na realizáciu. Ktokoľvek kto má záujem si ju môže priradiť a začať na nej pracovať.)
 - **2 - Working** (už je niekomu kto na nej pracuje priradená)
 - **3 - Done** (úloha je hotová a žiadna ďalšia práce už nie je potrebná)

Ešte sa mi tam pýta niečo na označenie úloh, ktoré je potrebné testovať. Poprípade označiť úlohy, kde chceme spraviť code review.

**Čo vy na to?**

> Ten workflow mávajú preto takýto, lebo používajú nástroj [Huboard](https://huboard.com/), ktorý sa dokáže pripojiť na GitHub a vytvoriť z neho Kanban dashboard.

**Comment by satano** [comment]
K typom nemám žiadne výhrady.

Ku workflow - je mi jasné, že to môže potrebovať nejaký externý nástroj, ale u nás to nie je nutné. *Backlog* sa môže realizovať pomocou tých Milestone-ov. *Ready* ani neviem presne na čo slúži &ndash; resp. to čo je v nejakom tom backlogu beriem ako že sa môže riešiť. *Done* je zbytočný. Za mňa úloha je *Done*, keď je uzavretá &ndash; načo navyše každej uzavretej priraďovať štítok. Možno ten *Working* má zmysel, aby bolo jasné, že sa na tom robí, ale to by sa možno zo začiatku dalo proste len priradením človeka k úlohe. A ktorá nemá nikoho priradeného, je stále voľná - či už len čaká na samotnú realizáciu, alebo sa len nejako pripomienkuje.

**Comment by DedrickX** [comment]
S issue type návrhmi súhlasím. Takže ako issue typu **discussion** je možné dať napr. otázku - *Čistý JavaScript vs TypeScript vs Babel.js*?
Tým pádom väčšina diskusií ku projektu bude prebiehať práve tu - nie v mailoch... To sa mi páči :)

**Comment by majco333** [comment]
Done je fakt asi zbytocny, Backlog a Ready ale kludne mozu byt lebo asi sa bezne stane, ze sa vytvoria issues, ale este ich nebude mozne robit (kvoli zavislostiam, otazkam...). Working moze tiez byt, nech sa hned na prvy pohlad vie, ze sa na tom maka. Za mna super, pekne...
Ten mileston mozes za mna vytvorit...

**Comment by Burgyn** [comment]
Oki, ja to ešte nechám chvíľu otvorené, aby sa vyjadrili viacerí. A potom to nejak zhrniem. Poprípade spíšem do Wiki.
* > Gabo : využiť _mileston_ na realizáciu backlogu si myslel ako? 
Mali by sme viacero _mileston_ podľa celkov, ako napríklad: Administrácia užívateľov / správa miestností / ...? 
Alebo by sme mali fakt len míľniky ako napríklad Rezervácia miestností 1.0/ Fórum 2.0 / ...?

**Comment by satano** [comment]
*Milestone* sa môže vytvoriť podľa &hellip; čohokoľvek. Môže to byť sprint, ale môže to byť aj UserStorky, v ktorej budú všetky tasky/chyby týkajúce sa nejakej časti programu. Beriem to tak voľne &ndash; ak niekto uzná za vhodné spraviť nejaký a zoskupiť podeň tasky, nech sa tak stane. A uvidíme čo to prinesie. :)

**Comment by ivansopoliga** [comment]
Typy ok.

Workflow by som, ale tiež dodržal tak ako je navrhnutý vyššie. Teraz by sa niektoré štítky možno dali poriešiť inak, ale ako bude pribúdať úloh môže byť dobré mať ich všetky označené. Okrem toho sa mi viac páči myšlienka mať úlohu v každej fáze označenú štítkom. Aby o jej stave nehovoril raz štítok a raz to, že má priradeného užívateľa atď. Mohlo by to byť výhodné aj z hľadiska externých nástrojov. Ak časom zistíme, že je to blbosť, môžme niečo vynechať.

**Comment by majco333** [comment]
Ivo dnes navrhol, ze niektore issues bude dobre po zapracovani prebrat osobne na stretku. Pridal by som novy stitok aj pre toto, aby sa to dalo potom lahko filtrovat...

**Comment by Burgyn** [comment]
Pridal som štítok **review**

**Comment by Burgyn** [comment]
Pridal som sekciu na používanie štítkov do WIKI. https://github.com/FunnyBean/IntraWeb/wiki/Pou%C5%BE%C3%ADvanie-%C5%A1t%C3%ADtkov

Túto tému uzatváram.
