### ISSUE TITLE
Konfigurácia Postmana alebo Fiddlera?

### ISSUE THREAD

**Issue by DedrickX** [FunnyBean/IntraWeb#53]
Ako by som si mohol nakonfigurovať Postman alebo Fiddler, aby som mohol robiť testovacie requesty na naše Controllery vyžadujúce autorizáciu?
Zatiaľ si viem dočasne vyhodiť atribút Authorize, ale viem že sa tie autorizačné tokeny a vecičky v týchto nástrojoch dajú nastaviť... Akurát sa v tom vôbec nevyznám :)

**Comment by Burgyn** [comment]
Ahoj Postman sa da jednoducho nastavit tak ze mu zapnes aby si z Chromu preberal cookies (zapnut interceptor). Nasledne sa len v chrome prihlasis. Bohuzial este autorizaciu nemame zapracovanu, takze  docasne mas najjednoduchsie zakomentovat autorizacny atribut.

**Comment by majco333** [comment]
Uzavrieme?
