### ISSUE TITLE
Implementovať odosielanie a formátovanie e-mailov

### ISSUE THREAD

**Issue by satano** [FunnyBean/IntraWeb#59]
Implementácia musí podporovať:

- [ ] Rôzne **typy** emailov, každý môže svoje vlastné dáta.
- [ ] **Jedna** šablóna pre všetky typy emailov.

**Comment by satano** [comment]
Trochu som sa venoval emailom a mám k tomu zopár postrehov, ktoré by bolo dobré prehodnotiť.

Momentálne máme nejakú vygenerovanú službu `IEmailService`, ktorá ako parameter má email adresáta, predmet, správa samotná a ešte oslovenie. K tomu je controller `EmailController`. Ako pokus či vieme odoslať email je to fajn, ale na reálne posielanie je to za mňa nepoužiteľné. Vychádzam z toho, že emailov bude **_X_ rôznych typov**:

- Nejaký uvítací po registrácii.
- Email o zmene hesla pri zabudnutí.
- Oznamovací o aktivite: napríklad rezervácia miestnosti, rezervácia auta...
- Email správcovi o vážnej chybe ak nejaká nastala.
- atď.

Toto je len tak čo ma narýchlo napadlo, isto sa to postupne vykryštalizuje. Ale email má nejakú hlavičku, pätu a samotné telo a všetky by mali mať rovnaký formát. Zatiaľ pre jednoduchosť sa meniť bude len telo emailu podľa typu. Ale každý typ má nejaké svoje vlastné dáta. Napr. mail o zabudnutom hesle má vygenerovaný odkaz, kde si človek heslo zmení. Mail o rezervácii miestnosti bude mať informácie o rezervácii (okrem nejakého štandardného textu v okolo tele)...

Napadajú ma dve možnosti ako to riešiť. Buď každý typ emailu má vlastné API so svojimi parametrami a teda zrejme vlastný controller. Toto sa mi moc nepáči. Alebo teda jeden controller a jedna služba, kde jeden z nutných parametrov je typ emailu a ostatné sú rôzne podľa typu. Služba sa už postará (resp. ďalšie pomocné služby) o správne naformátovanie a naplnenie šablóny a odoslanie.

Nejaké pripomienky, tipy, nápady...? Ak nie, začal by som to týmto smerom robiť.

**Comment by majco333** [comment]
Jasne, prvym krokom bolo iba vediet odoslat email. Aj ten controller vznikol iba kvoli testovaniu...

Ja som urcite iba za 1 controller na emaily, za mna ides dobrym smerom.

Tu sablonu html v resources sa ti nejako podarilo vyriesit?

**Comment by Burgyn** [comment]
Môj názor:
IMailService je náš interfejs popisujúci službu na odosielanie emailov.
Máme k nemu implementáciu, ktorá vie reálne odoslať naformátovaný email. O
formátovanie sa stará IEmailFormatter.
EmailController vznikol len na otestovanie či nám funguje odosielanie
emailov. Reálne sa používať nebude.
Každý controller, alebo iná služba, ktorá potrebuje odosielať email (či už
je to controller na správu používateľov, rezervačný controller, ...) by mal
dostať pomocou IoC kontajnera injektnutú implemnetáciu IEmailService a to
čo odosiela by si mal riešiť vo vlastnej réžií.
Samozrejme to môže byť extrahované do samostatných tried. Napríklad, keď
budeme generovať telo emailu pre informácie o rezervácií, tak si vytvoríme
triedu, ktorá to bude vedieť vygenerovať.

Ale nemyslím si, že na to budú vznikať controllery. Pretože controller je
miesto na spracovanie requestu, a zatiaľ si nemyslím, že budeme mať
requesty na odosielanie emailov. Väčšina emailov sa bude generovať na
strane servera po nejakej akcií, ktorú spracováva iný controller.



2016-03-01 16:19 GMT+01:00 Stano Peťko <notifications@github.com>:

> Trochu som sa venoval emailom a mám k tomu zopár postrehov, ktoré by bolo
> dobré prehodnotiť.
>
> Momentálne máme nejakú vygenerovanú službu IEmailService, ktorá ako
> parameter má email adresáta, predmet, správa samotná a ešte oslovenie. K
> tomu je controller EmailController. Ako pokus či vieme odoslať email je
> to fajn, ale na reálne posielanie je to za mňa nepoužiteľné. Vychádzam z
> toho, že emailov bude *X rôznych typov*:
>
>    - Nejaký uvítací po registrácii.
>    - Email o zmene hesla pri zabudnutí.
>    - Oznamovací o aktivite: napríklad rezervácia miestnosti, rezervácia
>    auta...
>    - Email správcovi o vážnej chybe ak nejaká nastala.
>    - atď.
>
> Toto je len tak čo ma narýchlo napadlo, isto sa to postupne
> vykryštalizuje. Ale email má nejakú hlavičku, pätu a samotné telo a všetky
> by mali mať rovnaký formát. Zatiaľ pre jednoduchosť sa meniť bude len telo
> emailu podľa typu. Ale každý typ má nejaké svoje vlastné dáta. Napr. mail o
> zabudnutom hesle má vygenerovaný odkaz, kde si človek heslo zmení. Mail o
> rezervácii miestnosti bude mať informácie o rezervácii (okrem nejakého
> štandardného textu v okolo tele)...
>
> Napadajú ma dve možnosti ako to riešiť. Buď každý typ emailu má vlastné
> API so svojimi parametrami a teda zrejme vlastný controller. Toto sa mi moc
> nepáči. Alebo teda jeden controller a jedna služba, kde jeden z nutných
> parametrov je typ emailu a ostatné sú rôzne podľa typu. Služba sa už
> postará (resp. ďalšie pomocné služby) o správne naformátovanie a naplnenie
> šablóny a odoslanie.
>
> Nejaké pripomienky, tipy, nápady...? Ak nie, začal by som to týmto smerom
> robiť.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FunnyBean/IntraWeb/issues/59#issuecomment-190767579>.
>



-- 
Prajem pekný zvyšok dňa,
Ing. Milan Martiniak

**Comment by majco333** [comment]
V podstate ma @Burgyn pravdu, len mi napadol scenar, kedy by mozno controller stal za zvazenie. Napr. ked Android appka, by chcela odoslat nejaky typ emailu. Ale je pravda, ze to moze byt riesene nepriamo volanim inej akcie ineho controllera, ktory druhotne email odosle.

**Comment by Burgyn** [comment]
Aj mňa to napadlo :-), ale povedal som si, že by sme mali ísť YAGNI
prístupom a spraviť controller, až keď ho bude treba.

2016-03-01 19:37 GMT+01:00 Majo Mikula <notifications@github.com>:

> V podstate ma @Burgyn <https://github.com/Burgyn> pravdu, len mi napadol
> scenar, kedy by mozno controller stal za zvazenie. Napr. ked Android appka,
> by chcela odoslat nejaky typ emailu. Ale je pravda, ze to moze byt riesene
> nepriamo volanim inej akcie ineho controllera, ktory druhotne email odosle.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FunnyBean/IntraWeb/issues/59#issuecomment-190845742>.
>



-- 
Prajem pekný zvyšok dňa,
Ing. Milan Martiniak

**Comment by majco333** [comment]
Suhlas...

**Comment by satano** [comment]
Implementované aj šablóny aj základ emailov. API rozhranie pre emaily zatiaľ na testovanie ostalo.
