### ISSUE TITLE
Pridanie logovania chyb do projektu

### ISSUE THREAD

**Issue by majco333** [FunnyBean/IntraWeb#6]
Cielom je dozvediet sa o kazdej chybe, ktora v projekte nastane.

Moj navrh je pouzit [Elmah](http://www.asp.net/web-forms/overview/older-versions-getting-started/deploying-web-site-projects/logging-error-details-with-elmah-cs) a logovat odosielanim na google emailovy ucet (mozem aj do sqllite DB, ale to asi nie je treba).

Co vy na to?

**Comment by majco333** [comment]
Tak v ASP.NET 5 Elmah zatial nie je podporovany :-( Nejako by to mohlo ist cez toto [Entropy](https://github.com/aspnet/Entropy/tree/dev/samples/Logging.Elm), pozriem a uvidime.

**Comment by Burgyn** [comment]
K logovaniu majú aj dokumentáciu http://docs.asp.net/en/latest/fundamentals/logging.html

**Comment by majco333** [comment]
Hej to je to iste ako som nasiel. Len to mi pride ako fakt logovanie - zaslanie na email to asi neurobi. Pozriem na to...

**Comment by majco333** [comment]
Necham to zatial tak, pracuju este na podpore loggerov tretich stran. Zatial je dostupne logovanie, co spravil Mino (do konzoly...).
