### ISSUE TITLE
Ako spustate migracie DB?

### ISSUE THREAD

**Issue by majco333** [FunnyBean/IntraWeb#61]
Ako presne spustate migracie nad DB? Ja mam funkcny postup, ale nepaci sa mi moc. Je takyto:
- otvorim si konzolu
- nastavim cestu do adresara projektu
- musim najpr spustit "dnvm use 1.0.0-rc1-final" (lebo inak mi dnx prikaz nepozna)
- potom dam "dnx ef migrations add newMigrationName"
- a nakoniec "dnx ef database update"

Nejde to nejako priamo, mozno jednoduchsie z VS?

**Comment by motycak** [comment]
Migraciu vies spustit aj z Package Manager Console, pomocou prikazov
Ja som iba raz zadaval (prvykrat)  dnvm use1.0.0 ... teraz to uz nemusim zadavat..
a treba sa v Package Mager Console pomocou prikazu "cd" presunut do adresara \src\IntraWeb

**Comment by majco333** [comment]
Neslo mi to, ale po "dnvm upgrade" mi to uz ide. Diki moc :)
