### ISSUE TITLE
Notifikácie z Wiki

### ISSUE THREAD

**Issue by majco333** [FunnyBean/IntraWeb#63]
Už ma štvalo, že z po zmene vo wiki časti sa o tom človek nedozvie. 

Po troche googlenia je tu riešenie - RSS feed: https://github.com/FunnyBean/IntraWeb/wiki.atom

V Outlooku mi to ide, v Thunderbirde zatial nie...

**Comment by Burgyn** [comment]
Super. 
Ja používam feedly ako čítačku RSS a zobrazuje sa to tam v pohode.

Ďakujem Majo.
