### ISSUE TITLE
Admin template

### ISSUE THREAD

**Issue by majco333** [FunnyBean/IntraWeb#64]
Co by ste povedali na takuto admin template?
https://rdash-angular2.herokuapp.com/

Je to free projekt v Angular2. Viac tu: https://github.com/ziyasal/rdash-angular2

**Comment by Burgyn** [comment]
Mne sa páči.

**Comment by satano** [comment]
Pekné to je. Len sú _natémované_ aj iné typy stránok, alebo len tento dashboard? nejak nič iné nevidím. Alebo to už by sme si sami vyrobili niečo ďalšie na základe tohoto?

**Comment by majco333** [comment]
Nie toto je cislo iba admin template. Je to len navrh, padlo mi to do oka ked som nieco hladal. Uzivatelske stranky asi budu vyzerat inak, ci by sa dalo nieco obkukat odtialto zatial neviem...

**Comment by Burgyn** [comment]
uzavrieme?

**Comment by satano** [comment]
Pokojne.
