### ISSUE TITLE
API Response status pre neexistujuci objekt

### ISSUE THREAD

**Issue by majco333** [FunnyBean/IntraWeb#65]
Uz sme sa o tom bavili, ale neuzavreli - ak pride poziadavka na api (Get alebo Update podla ID) a objekt s Id neexistuje tak dame aku odpoved?

Aktualne je:
// Equivalent to HTTP status 204. System.Net.HttpStatusCode.NoContent indicates
// that the request has been successfully processed and that the response is intentionally blank.
**NoContent (204)**

Navrhujem:
// Equivalent to HTTP status 404. System.Net.HttpStatusCode.NotFound indicates that
// the requested resource does not exist on the server.
**NotFound (404)**

**Comment by satano** [comment]
Takže mne aj mentálne predtým, a teraz aj z tých anglických popisov vychádza, že je to **404**.

204 _response is Intentionally blank_ - teda vlastne sa dáva človeku na známosť, že všetko je OK, a odpoveď je naschvál prázdna.

404 _resource does not exist_ - požadovaný zdroj neexistuje. Čo je pravda, pretože som zadal blbé IDčko a zadný človek/miestnosť/hocičo naozaj neexistuje.

**Comment by Burgyn** [comment]
Súhlasím.
Prerobím RoomsController.

2016-03-05 10:54 GMT+01:00 Stano Peťko <notifications@github.com>:

> Takže mne aj mentálne predtým, a teraz aj z tých anglických popisov
> vychádza, že je to *404*.
>
> 204 *response is Intentionally blank* - teda vlastne sa dáva človeku na
> známosť, že všetko je OK, a odpoveď je naschvál prázdna.
>
> 404 *resource does not exist* - požadovaný zdroj neexistuje. Čo je
> pravda, pretože som zadal blbé IDčko a zadný človek/miestnosť/hocičo naozaj
> neexistuje.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FunnyBean/IntraWeb/issues/65#issuecomment-192614881>.
>



-- 
Prajem pekný zvyšok dňa,
Ing. Milan Martiniak
