### ISSUE TITLE
Názvoslovie projektu

### ISSUE THREAD

**Issue by Burgyn** [FunnyBean/IntraWeb#69]
Na meetingu #68 sme sa rozprávali o zjednotení názvoslovia nášho projektu.
Pretože niekde používame IntraWeb, niekde FunnyBean a niekde KrosBook.

Táto issue je o tom aby sme si zjednotili názvoslovie. Teda sa aj dohodli, ako čo budeme nazývať.

Pokiaľ si dobre pamätám tak od Gaba padlo niečo nasledovné:

> FunnyBean je naša "firma" a IntraWeb náš produkt.

**Comment by Burgyn** [comment]
Nikto nič?

**Comment by satano** [comment]
:smile: Ja som trochu pozabudol na túto issue. Každopádne zjednotiť by sa to mohlo. Stále to beriem tak ako si napísal, že to beriem. Takže len treba zatiaľ ujednotiť, či budeme používať _KrosBook_, alebo _IntraWeb_. Mne osobne je to jedno. Ak sa nikto neozve, nechajme KrosBook, ako to bolo na Shipit-e.

**Comment by motycak** [comment]
Názov produktu: **IntraWeb**
Názov tímu ("firmy"): **KrosTeam**   -  (Možno raz sa zapojí - celá firma... Každý vo firme by sa mal niekam posúvať, toto môže byť základ e-learningu...  Názov by mal evokovať: Tímovosť, Spoluprácu, Otvorenosť...  )

**Comment by majco333** [comment]
Ja som za: FunnyBean je naša "firma" a IntraWeb náš produkt.

**Comment by DanielHolan** [comment]
Ja som za názov teamu (firmy) FunnyBean - to sme si už odhlasovali na začiatku. 
Názov projektu IntraWeb, ale nemám nič ani proti KrosBook - prípadne môžeme odhlasovať na stretku.

**Comment by DedrickX** [comment]
Tiež mi to sedí tak - FunnyBean ako tím/firma a IntraWeb ako produkt...

**Comment by majco333** [comment]
@satano pozries, ci treba niekde nahradit v projekte nazov projektu na IntraWeb?

**Comment by satano** [comment]
V podstate ešte sa nikde nepoužíva nič. _KrosBook_ je len pokusne v jednej tej emailovej šablóne - ale to zrušíme až keď sa už bude robiť šablóna na ostro. Inak je _IntraWeb_: názvy projektov, menný priestor... Ako text sa to ešte nevyskytuje nikde - aspoň som nič nenašiel.

**Comment by Burgyn** [comment]
Tak v tom prípade OK :-)

2016-03-29 21:02 GMT+02:00 Stano Peťko <notifications@github.com>:

> V podstate ešte sa nikde nepoužíva nič. *KrosBook* je len pokusne v
> jednej tej emailovej šablóne - ale to zrušíme až keď sa už bude robiť
> šablóna na ostro. Inak je *IntraWeb*: názvy projektov, menný priestor...
> Ako text sa to ešte nevyskytuje nikde - aspoň som nič nenašiel.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/FunnyBean/IntraWeb/issues/69#issuecomment-203052829>
>



-- 
Prajem pekný zvyšok dňa,
Ing. Milan Martiniak
