### ISSUE TITLE
Angular 1 vs. 2 a JavaScript vs. TypeScript

### ISSUE THREAD

**Issue by ivansopoliga** [FunnyBean/IntraWeb#9]
Čo vy na to? Ja som za verziu 2. Keď staviame projekt na samých beta a rc technológiách :-) Za rok dva to bude pravdepodobne štandard, tak načo ísť do niečoho neaktuálneho. Samozrejme z toho vyplývajú podobné problémy ako pri asp.net. Menej hotových riešení a diskusii na internete.

**Comment by DedrickX** [comment]
###### Angular 1 alebo 2
**Ja osobne som za Angular 2**. Je mi sympatické, že si dovolili s novou verziou urobiť skutočnú generačnú zmenu vo filozófii. Hlavne kvôli tomu zožali toľko nevôle od komunity... no oni len reagujú na vývoj technológií. Začalo to projektom Polymer.js, prichádzajú nové špecifikácie v HTML/CSS/JS, rysuje sa budúcnosť v HTML komponentoch a Shadow-DOM... 
Angular 1 bude naďalej vo svete vo veľkom používaný, lebo je obľúbený a veľmi rozšírený, ale neviem či sa mi chce učiť používať knižnicu, ktorá to má už dávno zrátané.

###### JavaScript vs TypeScript vs iné "kompilátory" JavaScriptu
Čistý JavaScript v jeho "súčasnej" podobe mi je vrcholne nesympatický - žiadna "rozumná" modularita, prapodivne sa chovajúci *var*, cyklus *for* bez podpory iterable objektov atď. atď.
Ak chceme mať produkt, ktorý podporuje aj exotické alebo staršie prehliadače a pritom by sme radi využívali užitočné funkčnosti zo špecifikácie ECMAScript 6+, potrebujeme nejaký kompilátor... Tie v posledných rokoch začali frčať spolu s kompilátormi/preprocesormi na CSS (napr. LESS) a inými prapodivnosťami. 
V tomto sa orientujem iba zhruba, všimol som si že Google Angular tím sa vyprdol na ich vlastný Dart a začal úzko spolupracovať s MS TypeScript tímom - to bolo pre mňa celkom škoujúce :stuck_out_tongue_closed_eyes:.
**Takže som za TypeScript alebo Babel...**

**Comment by Burgyn** [comment]
Ja som za **Angular 2**. Čo sa týka dokumentácie tak ta je už celkom slušná https://angular.io/docs/ts/latest/index.html

Čo sa týka javascriptu tak sa tiež prikláňam k **TypeScript**-u.

**Comment by majco333** [comment]
Tiez som za 2

**Comment by majco333** [comment]
Uzatvarame?

**Comment by satano** [comment]
Tak hej :)
